# Generated by Django 5.2.3 on 2025-06-13 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publisher", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="deposits/")),
                (
                    "format",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("EPUB", "EPUB")], max_length=10
                    ),
                ),
                ("isbn", models.CharField(max_length=20)),
                ("authors", models.CharField(max_length=255)),
                ("publication_date", models.DateField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.publisher",
                    ),
                ),
            ],
        ),
    ]
