# Generated by Django 5.2.3 on 2025-06-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="is_google_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publisheruser",
            name="is_google_account",
            field=models.BooleanField(default=False),
        ),
    ]
