# Generated by Django 5.2.3 on 2025-06-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0002_publisher_is_google_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="publisheruser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
